# Generated by Django 3.1.1 on 2020-10-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testme',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email Of Tester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testme',
            name='text',
            field=models.TextField(default='', max_length=500, verbose_name='Code Of Issue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testme',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='Name Of Tester'),
        ),
    ]
