# Generated by Django 3.1.1 on 2020-10-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201015_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='testme',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
