# Generated by Django 3.1.1 on 2020-10-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_testme_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('discraption', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='testme',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
    ]
