# Generated by Django 3.1.1 on 2020-10-15 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_projects_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='projects',
        ),
    ]
