# Generated by Django 3.1.1 on 2020-10-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_projectsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmodel',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='Discraption',
            field=models.TextField(max_length=600, verbose_name='Discraption Of Project'),
        ),
    ]
