# Generated by Django 3.1.1 on 2020-10-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201015_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmodel',
            name='Image_Ditail',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='', verbose_name='Top Image Ditail'),
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='Image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='', verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
