# Generated by Django 3.1.1 on 2020-10-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201015_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmodel',
            name='Image2',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='', verbose_name='More Image Size 218 x 243'),
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='Image3',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='', verbose_name='More Image Size 218 x 243'),
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='Image4',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='', verbose_name='More Image Size 218 x 243'),
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='Image5',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='', verbose_name='More Image Size 218 x 243'),
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='Image6',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='', verbose_name='More Image Size 218 x 243'),
        ),
    ]
